# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $PASSWORD_DB
      POSTGRES_USER: $USERNAME_DB
      POSTGRES_DB: $DATABASE_NAME
      PGDATA: /data/postgres
    ports:
      - 5433:5432
    volumes:
      - postgres:/data/postgres


  scrapy_telbot:
    build:
      context: .
      dockerfile: ./compose/scrapy/Dockerfile
    depends_on:
      - postgres
    links:
      - postgres
    env_file: .env
    restart: always

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    depends_on:
      - postgres
      - scrapy_telbot
    ports:
      - 8000:8000
    links:
      - postgres
    env_file: .env
    restart: always

volumes:
    postgres:
