# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $PASSWORD_DB
      POSTGRES_USER: $USERNAME_DB
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - $PORT_DB:5432
    volumes:
      - ./db-data/:/var/lib/postgresql/data/:Z

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080

  redis:
    image: redis
    restart: always
    # environment:
    #   - name=value
    ports:
      - "$PORT_REDIS:6379"
