# Generated by Django 4.1.7 on 2023-09-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'domain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParseError',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'parse_error',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParseHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'parse_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contributor_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'parser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price_reg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_prolong', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_change', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registrator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('nic_handle1', models.TextField()),
                ('nic_handle2', models.TextField()),
                ('website', models.TextField()),
                ('city', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'registrator',
                'managed': False,
            },
        ),
    ]
