# Generated by Django 4.1.7 on 2023-10-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registrator',
            table='registrator',
        ),
    ]
