# Generated by Django 4.1.7 on 2024-01-04 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AlterModelOptions(
            name='registrator',
            options={'verbose_name': 'Регистратор', 'verbose_name_plural': 'Регистраторы'},
        ),
        migrations.AddField(
            model_name='price',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='price',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='parsehistory',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата парсинга'),
        ),
        migrations.AlterField(
            model_name='price',
            name='domain',
            field=models.CharField(choices=[('ru', 'Ru')], max_length=10, verbose_name='Домен'),
        ),
        migrations.AlterField(
            model_name='price',
            name='parse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.parsehistory'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_change',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Перенос'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_prolong',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Продление'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_reg',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Регистрация'),
        ),
        migrations.AlterField(
            model_name='registrator',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='registrator',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='registrator',
            name='website',
            field=models.TextField(verbose_name='Сайт'),
        ),
    ]
