# Generated by Django 4.1.7 on 2023-07-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regcomp',
            options={'managed': False},
        ),
    ]
