# Generated by Django 4.1.7 on 2024-02-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_price_options_alter_registrator_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='change_status',
            field=models.CharField(choices=[('V', 'valid'), ('A', 'absent')], default='V', max_length=1, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='price',
            name='prolong_status',
            field=models.CharField(choices=[('V', 'valid'), ('A', 'absent')], default='V', max_length=1, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='price',
            name='reg_status',
            field=models.CharField(choices=[('V', 'valid'), ('A', 'absent')], default='V', max_length=1, verbose_name='Статус'),
        ),
    ]
