# Generated by Django 4.1.7 on 2024-02-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_price_change_status_price_prolong_status_and_more'),
        ('catalog', '0003_teammember'),
        ('catalog', '0003_teammember_price_change_status_price_prolong_status_and_more'),
    ]

    operations = [
    ]
