# Generated by Django 4.1.7 on 2024-03-01 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_merge_20240225_1242'),
        ('catalog', '0004_merge_20240228_1048'),
    ]

    operations = [
    ]
