# Generated by Django 4.1.7 on 2024-03-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_merge_20240301_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='src/website/website/media/pictures/', verbose_name='Фото'),
        ),
    ]
